name: Frontend Client Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run vite build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build
